name: CI
on:
  push:
    branches: ["!main"]
jobs:
  lint-and-breaking-change-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Test
        run: make test
